name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        # The branch history will be preserved, but the content will be overwritten.
        # This is suitable for single-page applications or static sites.
        force_orphan: true
        publish_branch: master
